# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/aabed/Desktop/FinalProject475/FinalProject475.cache/wt [current_project]
set_property parent.project_path C:/Users/aabed/Desktop/FinalProject475/FinalProject475.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_ip C:/Users/aabed/Desktop/FinalProject475/FinalProject475.srcs/sources_1/ip/DataRam/DataRam.xci
set_property used_in_implementation false [get_files -all c:/Users/aabed/Desktop/FinalProject475/FinalProject475.srcs/sources_1/ip/DataRam/DataRam.dcp]
set_property is_locked true [get_files C:/Users/aabed/Desktop/FinalProject475/FinalProject475.srcs/sources_1/ip/DataRam/DataRam.xci]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top DataRam -part xc7a100tcsg324-1 -mode out_of_context
rename_ref -prefix_all DataRam_
write_checkpoint -noxdef DataRam.dcp
catch { report_utilization -file DataRam_utilization_synth.rpt -pb DataRam_utilization_synth.pb }
if { [catch {
  file copy -force C:/Users/aabed/Desktop/FinalProject475/FinalProject475.runs/DataRam_synth_1/DataRam.dcp C:/Users/aabed/Desktop/FinalProject475/FinalProject475.srcs/sources_1/ip/DataRam/DataRam.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}
if { [catch {
  write_verilog -force -mode synth_stub C:/Users/aabed/Desktop/FinalProject475/FinalProject475.srcs/sources_1/ip/DataRam/DataRam_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode synth_stub C:/Users/aabed/Desktop/FinalProject475/FinalProject475.srcs/sources_1/ip/DataRam/DataRam_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_verilog -force -mode funcsim C:/Users/aabed/Desktop/FinalProject475/FinalProject475.srcs/sources_1/ip/DataRam/DataRam_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode funcsim C:/Users/aabed/Desktop/FinalProject475/FinalProject475.srcs/sources_1/ip/DataRam/DataRam_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if {[file isdir C:/Users/aabed/Desktop/FinalProject475/FinalProject475.ip_user_files/ip/DataRam]} {
  catch { 
    file copy -force C:/Users/aabed/Desktop/FinalProject475/FinalProject475.srcs/sources_1/ip/DataRam/DataRam_stub.v C:/Users/aabed/Desktop/FinalProject475/FinalProject475.ip_user_files/ip/DataRam
  }
}

if {[file isdir C:/Users/aabed/Desktop/FinalProject475/FinalProject475.ip_user_files/ip/DataRam]} {
  catch { 
    file copy -force C:/Users/aabed/Desktop/FinalProject475/FinalProject475.srcs/sources_1/ip/DataRam/DataRam_stub.vhdl C:/Users/aabed/Desktop/FinalProject475/FinalProject475.ip_user_files/ip/DataRam
  }
}
