# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/aabed/Desktop/FinalProject475/FinalProject475.srcs/sources_1/ip/DataRam/DataRam.xci
# IP: The module: 'DataRam' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/aabed/Desktop/FinalProject475/FinalProject475.srcs/sources_1/ip/DataRam/DataRam_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DataRam'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/Users/aabed/Desktop/FinalProject475/FinalProject475.srcs/sources_1/ip/DataRam/DataRam.xci
# IP: The module: 'DataRam' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/aabed/Desktop/FinalProject475/FinalProject475.srcs/sources_1/ip/DataRam/DataRam_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DataRam'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
